[postgres]
database = "postgres"
user = "postgres"
password = "postgres"

[server]
host = "localhost"
port = 4001
mail_sender = "noreply@example.com"
web_client_url = "https://example.com"
public_key = "/keys/private_key.pem"
private_key = "/keys/public_key.pem"

[smtp]
host = "smtp.example.com"
port = 587
user = "smtpuser"
pass = "smtppassword"
