version: '3.7'

services:

  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=exch  
      - POSTGRES_PASSWORD=exch
      - POSTGRES_DB=exch
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sleep 5"]
      interval: 30s
      timeout: 8s
      retries: 3

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  turkey:
    depends_on:
      rabbits:
        condition: service_healthy
    build: ./turkey
    healthcheck:
      test: ["CMD-SHELL", "sleep 10"]
      interval: 30s
      timeout: 15s
      retries: 3

  iyan:
    depends_on:
      turkey:
        condition: service_healthy
      rabbits:
        condition: service_healthy
      postgres:
        condition: service_healthy
    build: ./iyan
    # image: sijibomi242/iyan:latest
    ports: 
      - "4001:4001"
    healthcheck:
      test: curl --fail http://localhost:4001/api/v1/hello || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - shared_keys:/keys
      - shared_tokens:/tokens

  egusi:
    depends_on:
      iyan:
        condition: service_healthy
      rabbits:
        condition: service_healthy
      postgres:
        condition: service_healthy
    build: ./egusi
    # image: sijibomi242/egusi:latest
    environment:
      - PORT=6000
    ports:
      - 6000:6000
    volumes:
      - shared_keys:/keys
      - shared_tokens:/tokens

  rabbits:
    container_name: rabbits
    image: rabbitmq:3-management-alpine
    environment: 
      RABBITMQ_ERLANG_COOKIE: erlang_dev_only_cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: exch
    ports:
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 20 

volumes:
  shared_keys:
    driver: local
    driver_opts:
      type: none
      device: ./keys
      o: bind
  shared_tokens:
    driver: local
    driver_opts:
      type: none
      device: ./tokens
      o: bind