version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exch
    ports:
      - "5433:5432"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
  # iyan:
  #   build: ./iyan
  #   environment: 
  #     - PORT=4001
  #   ports: 
  #     - 4001:4001
  #   volumes:
  #     - shared_keys:/keys

  # egusi:
  #   build: ./egusi
  #   environment:
  #     - PORT=6000
  #   ports:
  #     - 6000:6000
  #   volumes:
  #     - shared_keys:/keys
  rabbits:
    container_name: rabbits
    image: rabbitmq:3-management-alpine
    environment: 
      RABBITMQ_ERLANG_COOKIE: erlang_dev_only_cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
networks:
  shared-network:
    external:
      name: elk_elk
volumes:
  shared_keys: