version: '3.7'

services:
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exch
    ports:
      - "5433:5432"
    logging:
      driver: json-file
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    logging:
      driver: json-file

  turkey:
    build: ./turkey
    
  iyan:
    depends_on:
      - turkey
      - rabbits
    build: ./iyan
    environment: 
      - PORT=4001
    ports: 
      - 4001:4001
    volumes:
      - shared_keys:/keys
      - shared_tokens:/tokens

  egusi:
    depends_on:
      - turkey
      - rabbits
      - iyan
    build: ./egusi
    environment:
      - PORT=6000
    ports:
      - 6000:6000
    volumes:
      - shared_keys:/keys
      - shared_tokens:/tokens

  rabbits:
    container_name: rabbits
    image: rabbitmq:3-management-alpine
    environment: 
      RABBITMQ_ERLANG_COOKIE: erlang_dev_only_cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    logging:
      driver: json-file
volumes:
  shared_keys:
    driver: local
    driver_opts:
      type: none
      device: ./keys
      o: bind
  shared_tokens:
    driver: local
    driver_opts:
      type: none
      device: ./tokens
      o: bind