version: '3.7'

# todo: remove all passwords from elk
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: 
      - logging-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
    networks:
      - logging-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - logging-network

# app stuff
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exch
    ports:
      - "5433:5432"
    logging:
      driver: json-file
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    logging:
      driver: json-file
  # iyan:
  #   build: ./iyan
  #   environment: 
  #     - PORT=4001
  #   ports: 
  #     - 4001:4001
  #   volumes:
  #     - shared_keys:/keys

  # egusi:
  #   build: ./egusi
  #   environment:
  #     - PORT=6000
  #   ports:
  #     - 6000:6000
  #   volumes:
  #     - shared_keys:/keys
  rabbits:
    container_name: rabbits
    image: rabbitmq:3-management-alpine
    environment: 
      RABBITMQ_ERLANG_COOKIE: erlang_dev_only_cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    logging:
      driver: json-file
    
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.9.0
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/data:/nginx/data
    logging:
      driver: json-file
volumes:
  shared_keys:
  elasticsearch:
networks: 
  logging-network:
    driver: bridge