filebeat.inputs:
  - type: log
    paths:
      - /var/log/nginx/access.log 
      - /var/log/nginx/error.log
      - /dev/stdout
      - /var/lib/docker/containers/*/*.log
    containers.ids:
      - "*"
    processors:
      - add_docker_metadata: ~
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
output.logstash:
  hosts: ["logstash:5044"] 
output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'