packer {
  required_plugins {
    googlecompute = {
      source  = "github.com/hashicorp/googlecompute"
      version = "~> 1"
    }
  }
}

variable "project" {
  type    = string
  default = "winged-ratio-399207"
}

variable "service_account" {
  type    = string
  default = "../secrets/winged-ratio-399207-9c8ec20121c8.json"
}

variable "ssh_key" {
  type    = string
  default = "../secrets/id_rsa"
}

variable "zone" {
  type    = string
  default = "us-central1-a"
}

source "googlecompute" "autogenerated_1" {
  account_file        = "${var.service_account}"
  image_name          = "exch-2023-09-16"
  project_id          = "${var.project}"
  source_image_family = "centos-7"
  ssh_username        = "packer"
  zone                = "${var.zone}"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "file" {
    destination = "/tmp/id_rsa"
    source      = "${var.ssh_key}"
  }

  provisioner "shell" {
    execute_command = "sudo -E -S sh '{{ .Path }}'"
    script          = "./setup.sh"
  }

}
