name: iyan:image
on:
  push:
    branches:
      - main
    paths:
      - 'iyan/**'
  pull_request:
    branches:
      - main
    paths:
      - 'iyan/**'
jobs:
  test:
    name: image-iyan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iyan
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t sijibomi242/iyan:latest -t sijibomi242/iyan:${GITHUB_SHA::7}-${GITHUB_RUN_ID::5} .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sijibomi242/iyan --all-tags